#' Plot of HIV prevalence over time
#'
#' Plots the raw and adjusted HIV prevalence over time
#'
#' This function has been developed to plot HIV prevalence over time.  Both the raw and fully adjusted (obtained using the \link[ANCRTAdjust]{data_clean}, \link[ANCRTAdjust]{mt_adjust}
#' and \link[ANCRTAdjust]{imperfectcov_adjust} functions) HIV prevalence can be plotted and compared or just the fully adjusted prevalence can be plotted.  The time unit can be set to 
#' either yearly or by reporting period.
#' 
#' @param Data The dataframe output by \link[ANCRTAdjust]{imperfectcov_adjust}.  The following variables must be present:
#'  \itemize{
#'   \item \code{snu1}: The subnational unit 1.  If plots are to be generated for the different snu1s, the parameter bysnu1 = "TRUE" must 
#'   have been specified when running \link[ANCRTAdjust]{imperfectcov_adjust}.
#'   \item \code{Time}: The year and/or quarter that the data was collected.  If plots are to be generated by reporting period, the parameter 
#'   byperiod = "TRUE" must have been specified when running \link[ANCRTAdjust]{imperfectcov_adjust}.  If plots are to be generated by year, the parameter
#'   byyear = "TRUE" must have been specified when running \link[ANCRTAdjust]{imperfectcov_adjust}.
#'   \item \code{HIV_fulladjust}: The HIV prevalence adjusted for imperfect testing coverage and all previous adjustments (i.e. data cleaning and adjustment 
#'   for multiple testing, if performed).  Generated using the \link[ANCRTAdjust]{imperfectcov_adjust} function.
#'   \item{HIV_raw}: The HIV prevalence using the raw data. Generated using the \link[ANCRTAdjust]{imperfectcov_adjust} function.
#'  }
#' @param snu1 The snu1 for which the plot is generated.  "All" indicates that the plot include the entire country data (i.e. not snu1-specific). Default = "All".
#' @param time.unit "PERIOD" indicates that the results be plotted by reporting period.  "YEAR" indicates that the results be plotted by year. Default = "PERIOD".
#' @param HIV_raw "TRUE" indicates that both the fully adjusted and raw HIV prevalences be plotted.  "FALSE" indicates that only the fully
#' adjusted HIV prevalences be plotted. Default = "TRUE".
#' @param y.lim The y-axis upper limit. Default = 40.
#'
#' @import ggplot2
#'
#' @author Mathieu Maheu-Giroux
#' @author Brittany Blouin
#'
#' @return A plot of HIV prevalence over time.
#'
#' @export

plot_rawadjusted <- function(Data, snu1 = "All", time.unit = "PERIOD", HIV_raw = "TRUE", y.lim = 40){

  if(time.unit == "PERIOD" & HIV_raw == "TRUE"){
    Plot <-
    ggplot(Data[Data$Time < 9000 & Data$snu1 == snu1,], aes(Time)) +
    geom_line(aes(y = HIV_raw, color = "Raw HIV prevalence"), size=1) + geom_point(aes(y = HIV_raw, color = "Raw HIV prevalence"))+
    geom_line(aes(y = HIV_fulladjust, color = "Adjusted HIV prevalence"), size=1) + geom_point(aes(y = HIV_fulladjust, color = "Adjusted HIV prevalence"))+
    xlab("Time") +
    ylab("HIV Prevalence (%)") +
    ylim(c(0, y.lim))+
    theme(axis.text = element_text(size = 7), axis.title = element_text(size = 7), legend.position = "right")+
    scale_colour_manual(name="",
                      values=c("Adjusted HIV prevalence"="blue", "Raw HIV prevalence"="red"))
    return(Plot)
  }
  
  if(time.unit == "YEAR" & HIV_raw == "TRUE"){
    if(max(Data$Time) > 9999){
      Data <- Data[Data$Time > 9999,]
      Data$Time <- substr(Data$Time, 1, 4)
      Data$Time <- as.numeric(Data$Time)
    }
    if(max(Data$Time) <= 9999){
      Data <- Data[Data$Time < 9999,]
      Data$Time <- as.numeric(Data$Time)
    }
    Plot2 <-
      ggplot(Data[Data$snu1 == snu1,], aes(Time)) +
      geom_line(aes(y = HIV_raw, color = "Raw HIV prevalence"), size=1) + geom_point(aes(y = HIV_raw, color = "Raw HIV prevalence"))+
      geom_line(aes(y = HIV_fulladjust, color = "Adjusted HIV prevalence"), size=1) + geom_point(aes(y = HIV_fulladjust, color = "Adjusted HIV prevalence"))+
      xlab("Time") +
      ylab("HIV Prevalence (%)") +
      ylim(c(0, y.lim))+
      theme(axis.text = element_text(size = 7), axis.title = element_text(size = 7), legend.position = "right")+
      scale_colour_manual(name="",
                          values=c("Adjusted HIV prevalence"="blue", "Raw HIV prevalence"="red"))
    return(Plot2)
  }
  
  if(time.unit == "PERIOD" & HIV_raw == "FALSE"){
    Plot3 <-
      ggplot(Data[Data$Time < 9000 & Data$snu1 == snu1,], aes(Time)) +
      geom_line(aes(y = HIV_fulladjust, color = "Adjusted HIV prevalence"), size=1) + geom_point(aes(y = HIV_fulladjust, color = "Adjusted HIV prevalence"))+
      xlab("Time") +
      ylab("HIV Prevalence (%)") +
      ylim(c(0, y.lim))+
      theme(axis.text = element_text(size = 7), axis.title = element_text(size = 7), legend.position = "none")+
      scale_colour_manual(name="", values=c("Adjusted HIV prevalence"="blue"))
    return(Plot3)
  }
  
  if(time.unit == "YEAR" & HIV_raw == "FALSE"){
    if(max(Data$Time) > 9999){
      Data <- Data[Data$Time > 9999,]
      Data$Time <- substr(Data$Time, 1, 4)
      Data$Time <- as.numeric(Data$Time)
    }
    if(max(Data$Time) <= 9999){
      Data <- Data[Data$Time < 9999,]
      Data$Time <- as.numeric(Data$Time)
    }
    Plot4 <-
      ggplot(Data[Data$snu1 == snu1,], aes(Time)) +
      geom_line(aes(y = HIV_fulladjust, color = "Adjusted HIV prevalence"), size=1) + geom_point(aes(y = HIV_fulladjust, color = "Adjusted HIV prevalence"))+
      xlab("Time") +
      ylab("HIV Prevalence (%)") +
      ylim(c(0, y.lim))+
      theme(axis.text = element_text(size = 7), axis.title = element_text(size = 7), legend.position = "none")+
      scale_colour_manual(name="", values=c("Adjusted HIV prevalence"="blue"))
    return(Plot4)
  }

}